### ISSUE TITLE
RelationGroup should contain target identifier, currently only target object

### ISSUE THREAD

**Issue by Helmut-Ortmann** [RHEAGROUP/reqifsharp#10]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the ReqIFSharp
- [x] I have searched [open](https://github.com/RHEAGROUP/ReqIFSharp/issues) and [closed](https://github.com/RHEAGROUP/ReqIFSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Feature request: Access to target identifier in RelationGroup(if target object isn't available in *.reqif file, external link)

Given a *.reqif file with a RelationGroup where the target object isn't part of the reqif file (external link). It would be nice to get the identifier of that target object (SpecObject).

New/Changed Interface:
string CoreContent[i].SpecRelations.TargetIdentifier or so

The xml snippet. The identifier 'x0400000001330720' isn't specified in *.reqif. It's part of another file.
`
<SPEC-RELATION IDENTIFIER="x1500000001330753" LAST-CHANGE="2015-03-31T16:33:20+02:00">
    <TARGET>
        <SPEC-OBJECT-REF>x0400000001330720</SPEC-OBJECT-REF>
    </TARGET>
    <SOURCE>
        <SPEC-OBJECT-REF>x040000000133073F</SPEC-OBJECT-REF>
    </SOURCE>
    <TYPE>
        <SPEC-RELATION-TYPE-REF>SPECREL</SPEC-RELATION-TYPE-REF>
    </TYPE>
</SPEC-RELATION>
`
### Steps to Reproduce

only Interface extension.

### System Configuration

- ReqIFSharp version:
  - [1.3.2 ] ReqIFSharp:         
  - [ ] Other:              
- Environment (Operating system, version and so on): windows 10
- .NET Framework version: net 4.6.2
- Additional information:

**Comment by naronatrhea** [comment]
in the next release, such not-found references will not be null anymore but will represent an object of the right type (Specification for RelationGroup and SpecObject for SpecRelation) that only has their identifier set with a description mentioning that the reference could not be found.

**Comment by samatrhea** [comment]
Dear @Helmut-Ortmann, we published a new release on nuget which includes the requested functionality https://www.nuget.org/packages/ReqIFSharp/1.4.0 let us know if you need anything else

**Comment by Helmut-Ortmann** [comment]
Thanks a lot for your fast and competent action.

Best regards,

Helmut
