### ISSUE TITLE
 The string 'False' is not a valid Boolean value.; Line and position: 218, 36

### ISSUE THREAD

**Issue by Helmut-Ortmann** [RHEAGROUP/reqifsharp#11]
### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am running the latest version of the ReqIFSharp
- [x] I have searched [open](https://github.com/RHEAGROUP/ReqIFSharp/issues) and [closed](https://github.com/RHEAGROUP/ReqIFSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

ReqEdit outputs the error message:
Fatal (SCHEMA): Error: The 'IS-SIMPLIFIED' attribute is invalid - The value 'False' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:boolean' - The string 'False' is not a valid Boolean value.; Line and position: 218, 36

The reqif file contains 'False' and 'false' as boolean value. I only used the default value of the attribute. Most of the values are correct.

### Steps to Reproduce

Write a new ReqIF file.

### System Configuration

- ReqIFSharp version:
  - [ ] ReqIFSharp:  1.4.0       
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version: 4.6.2
- Additional information:

**Comment by samatrhea** [comment]
Seems the `AttributeValueXHTML.IsSimplified`is not serialized properly. Fix is being reviewed by the team, should be able to release a new nuget today or tomorrow.

**Comment by Helmut-Ortmann** [comment]
Thanks a lot for your quick answer.

**Comment by Helmut-Ortmann** [comment]
Hi,

it looks as if I've made an error because I can't reproduce the error any more. Sorry for that.

Best regards,

Helmut

**Comment by samatrhea** [comment]
@Helmut-Ortmann we did refactor the code, now it is inline with the way we serialize boolean in other places. We released nuget version 1.4.1

**Comment by Helmut-Ortmann** [comment]
thanks a lot for your quick response

**Comment by samatrhea** [comment]
@Helmut-Ortmann  working on a web based reqif viewer, check it out here: https://viewer.reqifsharp.org/ and let us know what you think!

**Comment by Helmut-Ortmann** [comment]
Hi,

I tried it with some reqif files. After load, nothing happens. No error message no hint that it is running/loading the reqif file.

![image](https://user-images.githubusercontent.com/5464876/146017005-cc8d0014-9418-4d7b-a504-50e5b594b35e.png)

**Comment by samatrhea** [comment]
once you have opened one, then hit the load button; next you should see a list of all the reqif docs in the imported file (reqif or reqifz). From there you can now navigate to the dashboard. in the coming days/weeks we will also implement being able to view all items in the reqif files

**Comment by Helmut-Ortmann** [comment]
I tried it the way you described it. I will try it again after days/weeks. 

Have you thought that users might not want to give away their IP (Intellectual Property)? Requirements might be critical and users don't want to risk anything.

**Comment by samatrhea** [comment]
@Helmut-Ortmann yes please, follow along. Feel free to provide me with feedback at https://github.com/RHEAGROUP/reqifviewer/issues.

And yes, I have thought about users not wanting to provide a third party with their requirements set. Therefore the application is 100% browser based and does not run on a server. It's a single page application that is loaded by the browser and then runs in the browser. No data is sent to any server apart from the web server logging from which IP address the SPA is requested. And, organizations can easily host the web application locally using a docker container: https://hub.docker.com/repository/docker/rheagroup/reqifviewer

**Comment by Helmut-Ortmann** [comment]
Thanks for your clarification! Looks good for me.
