### ISSUE TITLE
Investigate that all is covered by ReqIf sharp that was done in Reflex project.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/reqifsharp#15]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the ReqIFSharp
- [ ] I have searched [open](https://github.com/RHEAGROUP/ReqIFSharp/issues) and [closed](https://github.com/RHEAGROUP/ReqIFSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Provide some additional test cases with interoperability with DOORS with databases provided by ESA as examples.

### System Configuration

- ReqIFSharp version:
  - [ ] ReqIFSharp:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatrhea** [comment]
@alexatrhea can this be closed?
