### ISSUE TITLE
Default value is not serialized inside attribute definition

### ISSUE THREAD

**Issue by LBRNZ** [RHEAGROUP/reqifsharp#17]
### Description
I have a reqif that has default values for several attribute definitions. I can deserialize it and see the default values in the data structure, but when serializing it, the default values are missing

```
<ATTRIBUTE-DEFINITION-ENUMERATION LAST-CHANGE="2021-06-11T15:52:48+02:00" IDENTIFIER="_e5e971b3-62e3-4607-8696-f359c1ae85f3" MULTI-VALUED="false" LONG-NAME="Relevant Author" IS-EDITABLE="true">
	<DEFAULT-VALUE>
		<ATTRIBUTE-VALUE-ENUMERATION>
			<DEFINITION>
				<ATTRIBUTE-DEFINITION-ENUMERATION-REF>_e5e971b3-62e3-4607-8696-f359c1ae85f3</ATTRIBUTE-DEFINITION-ENUMERATION-REF>
			</DEFINITION>
			<VALUES>
				<ENUM-VALUE-REF>_6feb570f-8ad8-40d9-9517-5abd6fe6f63a</ENUM-VALUE-REF>
			</VALUES>
		</ATTRIBUTE-VALUE-ENUMERATION>
	</DEFAULT-VALUE>
	<TYPE>
		<DATATYPE-DEFINITION-ENUMERATION-REF>_1c895072-5968-46a7-ba03-9a3680a499c2</DATATYPE-DEFINITION-ENUMERATION-REF>
	</TYPE>
</ATTRIBUTE-DEFINITION-ENUMERATION>
```

- ReqIFSharp version:
  - [ ] ReqIFSharp:         3.0.0
- Environment (Operating system, version and so on):
- .NET Framework version: 4.7.2

**Comment by samatrhea** [comment]
would it be possible to attach a sample reqif file so we can fix the problem and write some unit tests using that sample file to make sure it behaves the way it should?

**Comment by LBRNZ** [comment]
I created a minimal demo case
[DefaultValueDemo.txt](https://github.com/RHEAGROUP/reqifsharp/files/6655521/DefaultValueDemo.txt)
Had to change the fileextension because of github. You can change it back to .reqif

**Comment by samatrhea** [comment]
@LBRNZ i think i managed to fix it, you can find the new release here https://www.nuget.org/packages/ReqIFSharp/3.0.1

**Comment by samatrhea** [comment]
@LBRNZ  working on a web based reqif viewer, check it out here: https://viewer.reqifsharp.org/ and let us know what you think!

**Comment by LBRNZ** [comment]
Looks like an interesting project to inspect the contents of reqif files. I encountered some problems when displaying indentions and html tables, but maybe it is still work in progress. I think it would be nice to enhance the navigation on the left side a little more to have more of a tree navigation so I can see where I am when stepping through the document.
