### ISSUE TITLE
Error defining custom DataTypes with v5

### ISSUE THREAD

**Issue by philipparndt** [RHEAGROUP/reqifsharp#37]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the ReqIFSharp
- [x] I have searched [open](https://github.com/RHEAGROUP/ReqIFSharp/issues) and [closed](https://github.com/RHEAGROUP/ReqIFSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
First of all thanks for the great library!

When defining custom DataTypes I get an error with v5. With v4 the document seems to be correct.
Do I miss something that I need to change for the upgrade?

### Steps to Reproduce

The following test case will pass with v4 and fail with v5
The error stack trace is:
```
The type ReqIFSharp.DatatypeDefinitionDate was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterReqIF.Write5_DatatypeDefinition(String n, String ns, DatatypeDefinition o, Boolean isNullable, Boolean needType)
```

```csharp
[Fact]
public void TestSerialize()
{
    var document = new ReqIF
    {
        Lang = "en",
        TheHeader = new ReqIFHeader(),
        CoreContent = new ReqIFContent()
    };

    var dateDefinition = new DatatypeDefinitionDate
    {
        Identifier = "dateDefinition",
        LongName = "Date",
        LastChange = new DateTime()
    };
    
    document.CoreContent.DataTypes.Add(dateDefinition);
    
    using var file = new TemporaryFile();
    var serializer = new ReqIfSerializer();
    serializer.Serialize(document, file.FileInfo.FullName);
    Assert.InRange(file.FileInfo.Length, 600, 700);
}
```

### System Configuration
- ReqIFSharp version:
  - [x] ReqIFSharp:         v5
  - [x] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version: net5.0
- Additional information:

**Comment by samatrhea** [comment]
Hi @philipparndt , let me check your code in a unit test and i get back to you

**Comment by philipparndt** [comment]
Hi @samatrhea thank you a lot! This was a mistake on my side, I'm sorry for that.
I missed that, the code was actually using a wrapper for doing the serialization instead of the original source from the library.
The wrapper was introduced to add an additional namespace to the resulting document. As the header should look like this:
`<REQ-IF xmlns="http://www.omg.org/spec/ReqIF/20110401/reqif.xsd" xmlns:xhtml="http://www.w3.org/1999/xhtml">`

you can close this issue but maybe it would be great to keep the test case in your PR.

**Comment by samatrhea** [comment]
It seems we are indeed missing the **xhtml** namespace in the serialized result. That should not be the case. I close this issue, i keep the extra unit test from the PR and open a new issue to investigate the missing xhtml namespace from the serialization result
