### ISSUE TITLE
External Object is not found when attributes are in wrong order

### ISSUE THREAD

**Issue by LBRNZ** [RHEAGROUP/reqifsharp#39]
The class https://github.com/RHEAGROUP/reqifsharp/blob/3f90b2aaa837cf4f553487cb61b7b911eb2ac6fd/ReqIFSharp/AttributeValue/AttributeValueXHTML.cs#L232 looks for external objects in XHTML strings in line 232. That doesn't work if the data Attribute is not in first position. When for example the type Attribute is in first position, no external objects are detected.

**Comment by samatrhea** [comment]
@LBRNZ can you add a reqif file that has this attribute not being in the first position, that will make it easier for me to fix the issue.

**Comment by LBRNZ** [comment]
[Spielwiese.zip](https://github.com/RHEAGROUP/reqifsharp/files/7892441/Spielwiese.zip)
No Problem

**Comment by samatrhea** [comment]
should be fixed, new nuget has been published to nuget.org, version 5.0.1
