### ISSUE TITLE
Feature Request - Parent Property in SpecHierarchy Objects

### ISSUE THREAD

**Issue by LBRNZ** [RHEAGROUP/reqifsharp#41]
### Feature Request
It would be nice to have the Parent Property in SpecHierarchy Objects like stated in the ReqIF Specification ([10.8.37 SpecHierarchy](https://www.omg.org/spec/ReqIF/1.2/PDF))

**Comment by samatrhea** [comment]
From the ReqIF specification you would like the library to be completed with:

'''
parent : SpecHierarchy [0..1]
Up link to previous level of SpecHierarchy (which owns this level).

'''

**Comment by LBRNZ** [comment]
Exactly. That would be really nice

**Comment by samatrhea** [comment]
The `SpecHierarchy` class has a property called `Container` which is the same as the `Parent` property. Should work, let me know whether it does

**Comment by LBRNZ** [comment]
Yeah I saw that and thought it wasn't working, because it was null. But I looked on the first element in Hierarchy and there it has to be null. That was stupid by me 😄Thanks fpr the advice anyways.
