### ISSUE TITLE
Exception occurs when deserializing a huge file

### ISSUE THREAD

**Issue by ishihara-ma** [RHEAGROUP/reqifsharp#43]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the ReqIFSharp
- [x] I have searched [open](https://github.com/RHEAGROUP/ReqIFSharp/issues) and [closed](https://github.com/RHEAGROUP/ReqIFSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I use the reqifsharp for deserialize a large ReqIF file, the program throw the exception.

It seems that the cause is that the position of the stream changes when the program reads the stream using ZipArchive().

I confirmed by debugging that the position of Stream does not return to 0 not only for ReqIF files but also for files with a large number of characters.

For example, is it possible to change the program to return the stream position to 0?

The sample file with the problem is attached below.

Thank you.

### Steps to Reproduce

https://github.com/RHEAGROUP/reqifsharp/blob/development/ReqIFSharp/ReqIFDeserializer.cs#L240

### System Configuration

sample-reqif file:  [sample.zip](https://github.com/RHEAGROUP/reqifsharp/files/9110712/sample.zip)  
- ReqIFSharp version:
  - [x] ReqIFSharp:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:.netstandard2.0
- Additional information:

**Comment by samatrhea** [comment]
Can you provide me with a bit more information:
   - can you provide me the `huge` file, if not, then
   - please specify what is huge (then i can see if i can reproduce)

**Comment by samatrhea** [comment]
@ishihara-ma can you provide me with the above information? it would be great to either get a sample file or an indication in kilobytes or megabytes what constitues a large file and what kind of information is in the ziparchive (perhaps large attachments?)

**Comment by ishihara-ma** [comment]
@samatrhea   
Sorry for the late reply.

The huge file is already attached in the System Configuration chapter.

The file is the data that was actually used by DOORS, with the values ​​replaced with empty strings.

I presume that the condition of being huge depends on the number of characters and the file size.

I'm sorry if my answer is out of your perception.

Thank you.

**Comment by samatrhea** [comment]
Found it, will try and reproduce.

**Comment by samatrhea** [comment]
@ishihara-ma: even though i could not reproduce the error in version 5.0.3 I have been working on version 6.0.0. In that version i could reproduce the error with your sample file (and others as well). I implemented your suggestion and set the input stream to position 0 prior to feeding it to the xmlreader. That indeed fixed the problem. I have published a release candidate of version 6.0.0 to nuget.org. Let me know whether this has indeed fixed this issue. Please read the release notes as there are some breaking changes in version 6.0.0 versus version 5.0.0 (the API has changed a bit). https://github.com/RHEAGROUP/reqifsharp/releases/tag/6.0.0-RC1
