### ISSUE TITLE
Wrong XML serialization of numeric values in WriteXml methods. XmlConvert.ToString has to be used.

### ISSUE THREAD

**Issue by humnose** [RHEAGROUP/reqifsharp#5]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the ReqIFSharp
- [x] I have searched [open](https://github.com/RHEAGROUP/ReqIFSharp/issues) and [closed](https://github.com/RHEAGROUP/ReqIFSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Numeric values have to be serialized using .NET XmlConvert class in order to create valid numeric XML strings. 
For example: In class DatatypeDefinitionReal the Min/Max values are written into the XML writer using ToString() method. This will produce invalid XML if local settings is not set to German.
To produce valid XML all values have to be converted into strings by using XmlConvert.ToString method.

### Steps to Reproduce
Set local settings of windows system to German settings and serialize a ReqIF document.

### System Configuration
Running windows with German local settings.

- ReqIFSharp version:
  - [x] ReqIFSharp:      1.3.1
  - [x] Other:              
- Environment (Operating system, version and so on): Windows 10, 1703
- .NET Framework version: 4.6
- Additional information:

**Comment by samatrhea** [comment]
@naron-rhea: do you have to have a look at this issue sometime this week?

**Comment by humnose** [comment]
Hi together,
I just created a fork of your project and will try to fix this.
Please stand by for my pull request :-)

**Comment by humnose** [comment]
One question: Why do you not use the [XmlElement] and [XmlAttrbute] attributes on your serializable classes and prefer overloading the Read/WriteXml methods?

**Comment by samatrhea** [comment]
nuget published at https://www.nuget.org/packages/ReqIFSharp/1.3.2

**Comment by samatrhea** [comment]
@humnose working on a web based reqif viewer, check it out here: https://viewer.reqifsharp.org/ and let us know what you think!
